package com.farshadtahmasbi.motionrecyclerview

class DataSource {
    val data = generateData()
    private fun generateData(): List<CharacterAdapter.Data> {
        return mutableListOf<CharacterAdapter.Data>().apply {
            add(
                CharacterAdapter.Data(
                    R.drawable.batman,
                    R.drawable.batman_h,
                    R.string.batman_title,
                    R.string.batman_desc
                )
            )
            add(
                CharacterAdapter.Data(
                    R.drawable.joker,
                    R.drawable.joker_h,
                    R.string.joker_title,
                    R.string.joker_desc
                )
            )
            add(
                CharacterAdapter.Data(
                    R.drawable.superman,
                    R.drawable.superman_h,
                    R.string.superman_title,
                    R.string.superman_desc
                )
            )
            add(
                CharacterAdapter.Data(
                    R.drawable.wonderwoman,
                    R.drawable.wonderwoman_h,
                    R.string.wonderwoman_title,
                    R.string.wonderwoman_desc
                )
            )
            add(
                CharacterAdapter.Data(
                    R.drawable.flash,
                    R.drawable.flash_h,
                    R.string.flash_title,
                    R.string.flash_desc
                )
            )

            add(
                CharacterAdapter.Data(
                    R.drawable.harleyquinn,
                    R.drawable.harleyquinn_h,
                    R.string.harleyquinn_title,
                    R.string.harleyquinn_desc
                )
            )
            add(
                CharacterAdapter.Data(
                    R.drawable.greenlantern,
                    R.drawable.greenlantern_h,
                    R.string.greenlantern_title,
                    R.string.greenlantern_desc
                )
            )
            add(
                CharacterAdapter.Data(
                    R.drawable.penguin,
                    R.drawable.penguin_h,
                    R.string.penguin_title,
                    R.string.penguin_desc
                )
            )
            add(
                CharacterAdapter.Data(
                    R.drawable.aquaman,
                    R.drawable.aquaman_h,
                    R.string.aquaman_title,
                    R.string.aquaman_desc
                )
            )
            add(
                CharacterAdapter.Data(
                    R.drawable.shazam,
                    R.drawable.shazam_h,
                    R.string.shazam_title,
                    R.string.shazam_desc
                )
            )
            add(
                CharacterAdapter.Data(
                    R.drawable.katana,
                    R.drawable.katana_h,
                    R.string.katana_title,
                    R.string.katana_desc
                )
            )
            add(
                CharacterAdapter.Data(
                    R.drawable.deadshot,
                    R.drawable.deadshot_h,
                    R.string.deadshot_title,
                    R.string.deadshot_desc
                )
            )
        }
    }
}